<TagChip>:
    size_hint: None, None
    adaptive_width: True
    height: dp(20)
    padding: dp(5)
    radius: dp(10)
    text_color: self.theme_cls.opposite_text_color
    theme_text_color: "Custom"
    font_style: "Body1"
    halign: "center"
    canvas.before:
        Color:
            rgba: self.tag_color
        RoundedRectangle:
            size: self.size
            pos: self.pos
            radius: self.radius
